### ISSUE TITLE
Needs a v1 release

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/publish-wheels-anaconda#11]
Does not look very stable to ask user to point to `@main`. Should do a `v1` release like everything else in https://github.com/OpenAstronomy/github-actions-workflows/blob/main/.github/workflows/publish.yml

Thanks!

**Comment by bsipocz** [comment]
I came into this repo to say the same, there should be a release tagged. The version number doesn't really matter, `v1` sounds fine, but nevertheless, there should be a tag.

cc @ConorMacBride @Cadair
